#
# $Id: Makefile 346460 2009-11-14 05:06:47Z ssiano $
#
# Copyright (c) 2008, Juniper Networks, Inc.
# All rights reserved.
#

.-include "Makefile.inc"

PROVIDER_POLICIES = 

.include <jnx.rrdl.mk>

