#
# $Id: Makefile 359317 2010-01-22 21:15:05Z ranjini $
#
# Copyright (c) 2006, Juniper Networks, Inc.
# All rights reserved.
#

# define the subdirs
SUBDIR = xmltags 

hostuilibs:
	(cd ${_CURDIR} && ${HOSTTOOL_ENV} ${.MAKE} HOSTPROG=yes all)

.include <bsd.subdir.mk>

