#
# $Id: Makefile 346460 2009-11-14 05:06:47Z ssiano $
#
# Copyright (c) 2006, Juniper Networks, Inc.
# All rights reserved.
#

# define the subdirectories to be built
SUBDIR = certs

.include <bsd.subdir.mk>
